version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kafka-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8200:8080
    environment:
       KAFKA_CLUSTERS_0_NAME: local
       KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:29092,host.docker.internal:29093,host.docker.internal:29094
       DYNAMIC_CONFIG_ENABLED: 'true'
       KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
       KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://10.0.5.2:8083
       KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://10.0.5.2:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kafka-network


 

networks:
  kafka-network:
    driver: bridge

volumes:
  db:
    driver: local
