---
version: '2'
services:

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.5.0
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_BOOTSTRAP_SERVERS: localhost:9092
      # KAFKA_REST_SECURITY_PROTOCOL: "$SECURITY_PROTOCOL"
      # KAFKA_REST_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG
      # KAFKA_REST_SASL_MECHANISM: $SASL_MECHANISM
      # KAFKA_REST_CLIENT_BOOTSTRAP_SERVERS: $BOOTSTRAP_SERVERS
      # KAFKA_REST_CLIENT_SECURITY_PROTOCOL: "SASL_SSL"
      # KAFKA_REST_CLIENT_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG
      # KAFKA_REST_CLIENT_SASL_MECHANISM: $SASL_MECHANISM