https://aleger-server.process.vn/api/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwOTM4NTYyLCJleHAiOjE2ODM1MzA1NjJ9.Mg3PXsjDcemHK6KiFjMej0aMe0c43tYcgJppM-FYp5Y
content-type: application/json